import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
train = pd.read_csv("bank-full.csv")
test = pd.read_csv("bank.csv")
print(train.head())
print(test.head())
print(train.info())
print(train.shape)
print(test.shape)
plt.figure(figsize=(12, 6))
sns.countplot(x='job', data=train, order=train['job'].value_counts().index)
plt.title('Distribution of Job Types')
plt.xlabel('Job Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
plt.show()
plt.figure(figsize=(14, 6))
sns.countplot(x='job', hue='y', data=train, order=train['job'].value_counts().index)
plt.title('Job Type vs. Subscription')
plt.xlabel('Job Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.show()
plt.figure(figsize=(10, 5))
sns.countplot(x='marital', hue='y', data=train, order=train['marital'].value_counts().index)
plt.title('Marital Status vs. Subscription')
plt.xlabel('Marital Status')
plt.ylabel('Count')
plt.show()
plt.figure(figsize=(6, 4))
sns.countplot(x='housing', hue='y', data=train, order=train['housing'].value_counts().index)
plt.title('Housing Loan Status vs. Subscription')
plt.xlabel('Housing Loan Status')
plt.ylabel('Count')
plt.legend(title='Subscription', loc='upper right', labels=['No', 'Yes'])
plt.show()
plt.figure(figsize=(6, 4))
sns.countplot(x='loan', hue='y', data=train, order=train['loan'].value_counts().index)
plt.title('Personal Loan Status vs. Subscription')
plt.xlabel('Personal Loan Status')
plt.ylabel('Count')
plt.legend(title='Subscription', loc='upper right', labels=['No', 'Yes'])
plt.show()
plt.figure(figsize=(10, 6))
sns.histplot(train['day'], bins=30, kde=False)
plt.title('Distribution of Last Contact Day')
plt.xlabel('Last Contact Day')
plt.ylabel('Count')
plt.show()